Name = input("what is your name ")
print("Oh HOW original isn't", Name, "one of those cringy 2000's names how does it feel to have one of the most generic names in the world")
Age = input("anyways how old are you ")
print("Wow your", Age, "and your still acting like 12 month old crybaby get a life")
Color = input("whats your favorete color so I can embarrise you more ")
print("wow another original chose", Color, "whats next your favorate food is avacado toast")
Hobby = input("whats your favorete hobby bet its just as boring as the rest of your awnsers ")
print("you like", Hobby, "heh nerd")
book = input("since you have such boring answers ill ask you a boring question whats your favorite book ")
print("that tracks that you like", book, "considering you like", Hobby, "anyways this was boring im moving on to someone worthy of my burns")